dag_id: "hexaware"
schedule_interval: '@hourly'
catchup: False
aws_conn_id: "'aws_default'"
sftp_conn_id: "'sftp_default'"
bucket_name: "'astronomer-dataprocessing-poc'"
source_folder: "'inbound/hexaware/'"
archived_folder: "'archived/'"
destination_folder: "'outbound/hexaware/'"
destination_download: "'/usr/local/airflow/workspace/'"