dag_id: "marriott"
schedule_interval: '@daily'
catchup: False
aws_conn_id: "'aws_default'"
sftp_conn_id: "'sftp_default'"
bucket_name: "'astronomer-dataprocessing-poc'"
source_folder: "'inbound/marriott/'"
archived_folder: "'archived/'"
destination_folder: "'outbound/marriott/'"
destination_download: "'/usr/local/airflow/workspace/'"